script: "rake test"
rvm:
  - 1.8.7
  - 1.9.3
gemfile:
  - Gemfile
env:
  - TEST=test_unit MOCHA_OPTIONS=debug
  - TEST=test_unit TEST_UNIT=true MOCHA_OPTIONS=debug
  - TEST=mini_test MOCHA_OPTIONS=debug
  - TEST=mini_test MINI_TEST=true MOCHA_OPTIONS=debug
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: Gemfile
      env: TEST=mini_test MOCHA_OPTIONS=debug
    