script: "rake test"
rvm:
  - 1.8.7
  - 1.9.3
gemfile:
  - gemfiles/stdlib/Gemfile.latest
  - gemfiles/test-unit/Gemfile.latest
  - gemfiles/minitest/Gemfile.latest
env:
  - RAKE_TEST_TASK=test:test_unit MOCHA_OPTIONS=debug
  - RAKE_TEST_TASK=test:mini_test MOCHA_OPTIONS=debug
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/stdlib/Gemfile.latest
      env: RAKE_TEST_TASK=test:mini_test MOCHA_OPTIONS=debug
