script: "rake test"
bundler_args: --verbose
rvm:
  - 1.8.7
  - 1.9.3
gemfile:
  - Gemfile
env:
  - RAKE_TEST_TASK=test:test_unit MOCHA_OPTIONS=debug
  - RAKE_TEST_TASK=test:test_unit USE_TEST_UNIT=true MOCHA_OPTIONS=debug
  - RAKE_TEST_TASK=test:mini_test MOCHA_OPTIONS=debug
  - RAKE_TEST_TASK=test:mini_test USE_MINI_TEST=true MOCHA_OPTIONS=debug
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: Gemfile
      env: RAKE_TEST_TASK=test:mini_test MOCHA_OPTIONS=debug
